### ISSUE TITLE
v8.0.2a released!

### ISSUE THREAD

**Issue by sammy2142** [sammy2142/LibreELEC.tv#1]
v.8.0.2a has just been released (based on LibreELEC 8.0.2 MR public build).
You will need to use the old manual update method:
https://wiki.libreelec.tv/index.php?title=HOW_TO:Update_LibreELEC#Updating_LibreELEC_using_the_Samba_shares

Downloads can be found on the releases page:
https://github.com/sammy2142/LibreELEC.tv/releases

**Comment by nonobio** [comment]
Thanks a lot :)
